### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by cab-p** [TV-Guidance/tvGuidance#2]
User can search for TV show/Movie

- [x] search returns image of similar tv shows/ movies
- [x] search returns name of similar tv shows/ movies
- [x] navigation to details view controller for each movie/ tv show

**Comment by ftanmoy** [comment]
I've hooked up the details view to display the poster image and the title of the results. We need to figure out how to pass the results from the search component to the other views (maybe with a local json file). Once we have that, everything should work.
